import { contextBridge, ipcRenderer, webUtils } from 'electron'

contextBridge.exposeInMainWorld('neoAnkiDesktop', {
  isDesktop: true,
  rendererReady: () => ipcRenderer.send('neo-anki:renderer-ready'),
  loadData: () => ipcRenderer.sendSync('neo-anki:load-data'),
  loadDataAsync: () => ipcRenderer.invoke('neo-anki:load-data-async'),
  saveData: (changes: unknown) => ipcRenderer.invoke('neo-anki:save-data', changes),
  exportBackup: () => ipcRenderer.invoke('neo-anki:export-backup'),
  exportRecoverySource: () => ipcRenderer.invoke('neo-anki:export-recovery-source'),
  restoreBackup: () => ipcRenderer.invoke('neo-anki:restore-backup'),
  resetData: () => ipcRenderer.invoke('neo-anki:reset-data'),
  createImportCheckpoint: () => ipcRenderer.invoke('neo-anki:create-import-checkpoint'),
  listMigrationRecoveryFiles: () => ipcRenderer.invoke('neo-anki:list-migration-recovery-files'),
  removeMigrationRecoveryFile: (kind: string, name: string) => ipcRenderer.invoke('neo-anki:remove-migration-recovery-file', kind, name),
  commitWorkspaceV4Import: (input: unknown) => ipcRenderer.invoke('neo-anki:commit-workspace-v4-import', input),
  loadWorkspaceV4ExportPayload: () => ipcRenderer.invoke('neo-anki:load-workspace-v4-export-payload'),
  loadWorkspaceV4Document: () => ipcRenderer.invoke('neo-anki:load-workspace-v4-document'),
  loadCardRendering: (cardId: string) => ipcRenderer.invoke('neo-anki:load-card-rendering', cardId),
  applyCoreWorkspacePatchV2: (patch: unknown) => ipcRenderer.invoke('neo-anki:apply-core-workspace-patch-v2', patch),
  reportDiagnostic: (diagnostic: unknown) => ipcRenderer.invoke('neo-anki:report-diagnostic', diagnostic),
  exportDiagnostics: () => ipcRenderer.invoke('neo-anki:export-diagnostics'),
  getReleaseInfo: () => ipcRenderer.invoke('neo-anki:get-release-info'),
  listExtensions: () => ipcRenderer.invoke('neo-anki:list-extensions'),
  listMarketplaceExtensions: () => ipcRenderer.invoke('neo-anki:list-marketplace-extensions'),
  stageMarketplaceExtension: (id: string, version: string) => ipcRenderer.invoke('neo-anki:stage-marketplace-extension', id, version),
  chooseExtensionPackage: () => ipcRenderer.invoke('neo-anki:choose-extension'),
  installExtension: (token: string) => ipcRenderer.invoke('neo-anki:install-extension', token),
  discardExtension: (token: string) => ipcRenderer.invoke('neo-anki:discard-extension', token),
  setExtensionEnabled: (id: string, enabled: boolean) => ipcRenderer.invoke('neo-anki:set-extension-enabled', id, enabled),
  confirmExtensionActivation: (id: string) => ipcRenderer.invoke('neo-anki:confirm-extension-activation', id),
  rollbackExtensionActivation: (id: string) => ipcRenderer.invoke('neo-anki:rollback-extension-activation', id),
  uninstallExtension: (id: string, deleteSecrets: boolean) => ipcRenderer.invoke('neo-anki:uninstall-extension', id, deleteSecrets),
  reloadForExtensions: () => ipcRenderer.invoke('neo-anki:reload-for-extensions'),
  claimExtensionCapability: (id: string) => ipcRenderer.invoke('neo-anki:claim-extension-capability', id),
  extensionNetworkFetch: (token: string, request: unknown) => ipcRenderer.invoke('neo-anki:extension-network-fetch', token, request),
  extensionApplyPatchV2: (token: string, patch: unknown) => ipcRenderer.invoke('neo-anki:extension-apply-patch-v2', token, patch),
  extensionCreateMediaV2: (token: string, request: unknown) => ipcRenderer.invoke('neo-anki:extension-create-media-v2', token, request),
  extensionSaveFileV2: (token: string, request: unknown) => ipcRenderer.invoke('neo-anki:extension-save-file-v2', token, request),
  extensionOpenExternalV2: (token: string, url: string) => ipcRenderer.invoke('neo-anki:extension-open-external-v2', token, url),
  extensionSecretReadBatchV2: (token: string, keys: string[]) => ipcRenderer.invoke('neo-anki:extension-secret-read-batch-v2', token, keys),
  extensionSecretStatusBatchV2: (token: string, keys: string[]) => ipcRenderer.invoke('neo-anki:extension-secret-status-batch-v2', token, keys),
  extensionSecretMutateBatchV2: (token: string, changes: unknown[]) => ipcRenderer.invoke('neo-anki:extension-secret-mutate-batch-v2', token, changes),
  extensionConfigReadV2: (token: string) => ipcRenderer.invoke('neo-anki:extension-config-read-v2', token),
  extensionConfigWriteV2: (token: string, value: unknown) => ipcRenderer.invoke('neo-anki:extension-config-write-v2', token, value),
  extensionContentListNotesV2: (token: string, query: unknown) => ipcRenderer.invoke('neo-anki:extension-content-list-notes-v2', token, query),
  extensionMigrationExportV2: (token: string) => ipcRenderer.invoke('neo-anki:extension-migration-export-v2', token),
  stageImportSource: (file: File) => ipcRenderer.invoke('neo-anki:stage-import-source', webUtils.getPathForFile(file)),
  inspectImportSource: (token: string, sourceFileToken: string) => ipcRenderer.invoke('neo-anki:inspect-import-source', token, sourceFileToken),
  extensionMigrationCommitV2: (token: string, input: unknown) => ipcRenderer.invoke('neo-anki:extension-migration-commit-v2', token, input),
  extensionCancelV2: (token: string, operationId: string) => ipcRenderer.invoke('neo-anki:extension-cancel-v2', token, operationId),
  syncStatus: () => ipcRenderer.invoke('neo-anki:sync-status'),
  syncListDevices: () => ipcRenderer.invoke('neo-anki:sync-list-devices'),
  syncCreateAccount: (endpoint: string) => ipcRenderer.invoke('neo-anki:sync-create-account', endpoint),
  syncRecoverAccount: (recoveryBundle: string) => ipcRenderer.invoke('neo-anki:sync-recover-account', recoveryBundle),
  syncNow: () => ipcRenderer.invoke('neo-anki:sync-now'),
  syncResolveConflict: (conflictId: string, choice: 'existing' | 'incoming') => ipcRenderer.invoke('neo-anki:sync-resolve-conflict', conflictId, choice),
  syncRotateRecovery: () => ipcRenderer.invoke('neo-anki:sync-rotate-recovery'),
  syncRevokeDevice: (actorId: string) => ipcRenderer.invoke('neo-anki:sync-revoke-device', actorId),
  syncDisconnect: () => ipcRenderer.invoke('neo-anki:sync-disconnect'),
  syncDeleteAccount: () => ipcRenderer.invoke('neo-anki:sync-delete-account'),
  onNavigate: (callback: (destination: string) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, destination: string) => callback(destination)
    ipcRenderer.on('neo-anki:navigate', listener)
    return () => ipcRenderer.removeListener('neo-anki:navigate', listener)
  },
})
